flake.lock: bump nixpkgs
We need a more recent rustc:

error: rustc 1.85.0 is not supported by the following packages:
  icu_collections@2.2.0 requires rustc 1.86
  icu_locale_core@2.2.0 requires rustc 1.86
  icu_normalizer@2.2.0 requires rustc 1.86
  icu_normalizer_data@2.2.0 requires rustc 1.86
  icu_normalizer_data@2.2.0 requires rustc 1.86
  icu_normalizer_data@2.2.0 requires rustc 1.86
  icu_properties@2.2.0 requires rustc 1.86
  icu_properties_data@2.2.0 requires rustc 1.86
  icu_properties_data@2.2.0 requires rustc 1.86
  icu_properties_data@2.2.0 requires rustc 1.86
  icu_provider@2.2.0 requires rustc 1.86
  idna_adapter@1.2.2 requires rustc 1.86

We also need to pply the same zlib-ng revert that
91e812f0698997c1d6449af2896439efe65ec2a5 did in nixpkgs.